services:
  edulution-mail:
    image: ghcr.io/edulution-io/edulution-mail
    restart: always
    container_name: edulution-mail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/edulution-mail:/srv/docker/edulution-mail
    environment:
      - MAILCOW_HOSTNAME=mail.dev.multi.schule
      - MAILCOW_PATH=/srv/docker/edulution-mail
      - KEYCLOAK_SECRET_KEY=UIZvGG0JVDZaUEvLElwBfuqA64gMWTIl
