services:
  edulution-mail:
    image: ghcr.io/edulution-io/edulution-mail
    container_name: edulution-mail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:${PWD}
    environment:
      - MAILCOW_HOSTNAME=mail.dev.multi.schule
      - MAILCOW_PATH=${PWD}
      - KEYCLOAK_SECRET_KEY=UIZvGG0JVDZaUEvLElwBfuqA64gMWTIl