name: Build SOGo docker image

on:
  push:
    branches: ["main", "dev", "dev-dennis"]
    paths:
      - 'sogo-docker/**'
      - '.github/workflows/build-sogo.yml'

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-docker-sogo
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tags for SOGo
        id: docker-tags-sogo
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "tags=ghcr.io/${{ github.repository }}-sogo:main,ghcr.io/${{ github.repository }}-sogo:latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "tags=ghcr.io/${{ github.repository }}-sogo:dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "dev-dennis" ]]; then
            echo "tags=ghcr.io/${{ github.repository }}-sogo:dev-dennis" >> $GITHUB_OUTPUT
          else
            echo "tags=ghcr.io/${{ github.repository }}-sogo:${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata (labels) for Docker
        id: meta-sogo
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}-sogo

      - name: Build SOGo docker container
        uses: docker/build-push-action@v4
        with:
          context: ./sogo-docker/
          file: ./sogo-docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker-tags-sogo.outputs.tags }}
          labels: ${{ steps.meta-sogo.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
